<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Albatross.CommandLine" Version="8.0.6" />
		<PackageReference Include="Albatross.CommandLine.Defaults" Version="8.0.6" />
		<PackageReference Include="Albatross.Config" Version="7.5.11" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Albatross.Logging\Albatross.Logging.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="serilog.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>